In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.linear_model import LinearRegression

In [2]:
df= pd.read_csv("insurance.csv")
df

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [3]:
# label encoding

In [4]:
df['sex'] = df['sex'].astype('category')
df['sex'] = df['sex'].cat.codes

In [5]:
df

age  sex   bmi  children smoker     region  expenses
0      19    0  27.9         0    yes  southwest  16884.92
1      18    1  33.8         1     no  southeast   1725.55
2      28    1  33.0         3     no  southeast   4449.46
3      33    1  22.7         0     no  northwest  21984.47
4      32    1  28.9         0     no  northwest   3866.86
...   ...  ...   ...       ...    ...        ...       ...
1333   50    1  31.0         3     no  northwest  10600.55
1334   18    0  31.9         0     no  northeast   2205.98
1335   18    0  36.9         0     no  southeast   1629.83
1336   21    0  25.8         0     no  southwest   2007.95
1337   61    0  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [6]:
df['smoker'] = df['smoker'].astype('category')
df['smoker'] = df['smoker'].cat.codes

In [7]:
df['region'] = df['region'].astype('category')
df['region'] = df['region'].cat.codes

In [8]:
df

age  sex   bmi  children  smoker  region  expenses
0      19    0  27.9         0       1       3  16884.92
1      18    1  33.8         1       0       2   1725.55
2      28    1  33.0         3       0       2   4449.46
3      33    1  22.7         0       0       1  21984.47
4      32    1  28.9         0       0       1   3866.86
...   ...  ...   ...       ...     ...     ...       ...
1333   50    1  31.0         3       0       1  10600.55
1334   18    0  31.9         0       0       0   2205.98
1335   18    0  36.9         0       0       2   1629.83
1336   21    0  25.8         0       0       3   2007.95
1337   61    0  29.1         0       1       1  29141.36

[1338 rows x 7 columns]

In [9]:
# to find dependent and independent variable

In [11]:
x=df.drop(columns='expenses')
x

age  sex   bmi  children  smoker  region
0      19    0  27.9         0       1       3
1      18    1  33.8         1       0       2
2      28    1  33.0         3       0       2
3      33    1  22.7         0       0       1
4      32    1  28.9         0       0       1
...   ...  ...   ...       ...     ...     ...
1333   50    1  31.0         3       0       1
1334   18    0  31.9         0       0       0
1335   18    0  36.9         0       0       2
1336   21    0  25.8         0       0       3
1337   61    0  29.1         0       1       1

[1338 rows x 6 columns]

In [12]:
y=df['expenses']
y

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...   
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.95
1337    29141.36
Name: expenses, Length: 1338, dtype: float64

In [13]:
# split

In [14]:
x_train,x_test,y_train,y_test =  train_test_split(x,y,test_size=0.3,random_state=42)

In [15]:
x_train.shape

(936, 6)

In [16]:
x_test.shape

(402, 6)

In [17]:
# train

In [18]:
reg=LinearRegression()

In [20]:
reg.fit(x_train,y_train)

LinearRegression()

In [21]:
# predict

In [51]:
predict=reg.predict([[19,0,27.9,0,1,3]])
predict

C:\Users\ELITEBOOK\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24859.85141395])

In [52]:
y_predict=reg.predict(x_train)
y_predict

array([ 1.40166046e+04,  8.30952948e+03,  1.33744202e+04,  3.63308897e+04,
        3.37796625e+04,  3.54810724e+04,  5.97706395e+03,  6.16875570e+03,
        1.67029303e+04,  8.39365450e+03,  3.77707328e+04,  4.81559508e+03,
        8.30395940e+03,  9.98142519e+03,  3.01757067e+04,  5.47069559e+03,
        3.46786931e+03,  1.67486713e+04,  3.74733936e+03,  6.22474595e+03,
        1.03826778e+04, -1.13170504e+03,  2.95494838e+04,  8.49714830e+03,
        9.96663557e+03,  5.71203863e+03,  7.47440363e+03,  1.15981056e+04,
        2.87812490e+04,  9.60998871e+03,  1.05914571e+04,  6.45987871e+03,
        4.34909320e+03,  7.21242672e+02,  7.92579145e+03,  1.13534945e+04,
        1.00232376e+04,  8.42898391e+03,  6.33356645e+03,  4.34152430e+03,
        7.53165248e+03,  3.36012633e+04,  3.36345687e+04,  2.96251339e+03,
        3.98309353e+04,  2.84079152e+04,  1.07031787e+04,  3.93384545e+03,
        1.70599423e+04,  3.48587160e+03,  9.01138267e+03,  2.95756002e+04,
        1.64590447e+04,  

In [23]:
# accuracy

In [24]:
reg.score(x_train,y_train)

0.7422691015689171

In [25]:
reg.score(x_test,y_test)

0.7694626233326285

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
onehotencoder=OneHotEncoder()

In [41]:
x=onehotencoder.fit_transform(df.region.values.reshape(-1,1)).toarray()

In [37]:
x

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [39]:
df

age  sex   bmi  children  smoker  region  expenses
0      19    0  27.9         0       1       3  16884.92
1      18    1  33.8         1       0       2   1725.55
2      28    1  33.0         3       0       2   4449.46
3      33    1  22.7         0       0       1  21984.47
4      32    1  28.9         0       0       1   3866.86
...   ...  ...   ...       ...     ...     ...       ...
1333   50    1  31.0         3       0       1  10600.55
1334   18    0  31.9         0       0       0   2205.98
1335   18    0  36.9         0       0       2   1629.83
1336   21    0  25.8         0       0       3   2007.95
1337   61    0  29.1         0       1       1  29141.36

[1338 rows x 7 columns]

In [42]:
# r2 score

In [46]:
from sklearn.metrics import r2_score

In [53]:
r2_score(y_train,y_predict)

0.7422691015689171